---
steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Log in to GitHub Container Registry
    uses: docker/login-action@v1
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GHCR_PAT }}

  - name: Run Super-Linter
    uses: enda-automation/test-enda-super-linter@latest
# You can view https://github.com/super-linter/super-linter#environment-variables
# to see a comprehensive list of all environment variables that can be passed
