name: 'Super-Linter'
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Super-Linter
        runs:
          using: 'docker'
          image: 'docker://ghcr.io/enda-automation/enda-super-linter:latest'  # x-release-please-version
        branding:
          icon: 'check-square'
          color: 'white'